# Generated by Django 6.0.2 on 2026-02-05 15:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive = credits added, Negative = credits deducted.', max_digits=12)),
                ('transaction_type', models.CharField(choices=[('earn', 'Credits Earned'), ('buy', 'Credits Bought'), ('sell', 'Credits Sold'), ('retire', 'Credits Retired'), ('expire', 'Credits Expired'), ('adjust', 'Admin Adjustment')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HashLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('event_type', models.CharField(choices=[('MINT', 'Mint Credit'), ('TRADE', 'Transfer Credit'), ('RETIRE', 'Retire Credit')], max_length=10)),
                ('from_entity', models.CharField(max_length=255)),
                ('to_entity', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField()),
                ('prev_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
