# Generated by Django 6.0.2 on 2026-02-05 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('reduction', 'Reduction Project'), ('emission', 'Emission Assessment')], max_length=20)),
                ('methodology', models.CharField(choices=[('solar_reduction', 'Solar Displacement'), ('efficiency_reduction', 'Energy Efficiency'), ('waste_reduction', 'Waste Recycling'), ('electricity_emission', 'Electricity Emissions'), ('fuel_emission', 'Fuel Emissions'), ('travel_emission', 'Travel Emissions')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('quarter', models.CharField(max_length=2)),
                ('ai_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('estimated_emissions_kg', models.FloatField(blank=True, null=True)),
                ('estimated_reduction_kg', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReductionProjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_capacity_kw', models.FloatField(blank=True, null=True)),
                ('annual_generation_kwh', models.FloatField(blank=True, null=True)),
                ('baseline_energy_kwh', models.FloatField(blank=True, null=True)),
                ('post_project_energy_kwh', models.FloatField(blank=True, null=True)),
                ('waste_recycled_kg', models.FloatField(blank=True, null=True)),
                ('estimated_reduction_kg', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reduction_data', to='core.carbonproject')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.CharField(choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], max_length=2)),
                ('electricity_kwh', models.FloatField()),
                ('diesel_liters', models.FloatField(default=0)),
                ('petrol_liters', models.FloatField(default=0)),
                ('natural_gas_m3', models.FloatField(default=0)),
                ('flight_km', models.FloatField(default=0)),
                ('car_km', models.FloatField(default=0)),
                ('waste_kg', models.FloatField(default=0)),
                ('recycled_waste_kg', models.FloatField(default=0)),
                ('estimated_emissions_kg', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'year', 'quarter')},
            },
        ),
    ]
